### ISSUE TITLE
Qgeolistest

### ISSUE THREAD

**Issue by Bernard13090** [Oslandia/QGIS_CI#1]
### What is the bug or the crash?

This issue follows Sébastien Peillet  ant Qgeolistest team presentation .

I am in charge of looking at how to implement QGeologist on the site.

In order to be able to apprehend all the installation and server problems, I tried to make the Tutorial https://oslandia.gitlab.io/qgis/QGeoloGIS/tutorial.html

I manage to have Dummy points, but when I want to continue with station, I come across service='qgeologistest' sslmode=disable and definition of service "geologistest" not found !!!

At the end after pressing cancel multiple times I come across a table with in the Data Source column:
for rain => service='qgeologistest' sslmode=disable key='id' checkPrimaryKeyUnicity='0' table="qgis". "measure_rain" sql=

 I must say that I do not know what that means except that my source is not good. How to create the service with pgAdmin4 .

I'm on WIN10 with pgsql 15.2 QGis Desktop 3.28.3 and python 3.7.9.

Can you find me a motion for resolution.

Best regards

Bernard

### Steps to reproduce the issue

Station opening

### Versions

QGis Desktop 3.28.3 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Sorry for using this item but i need to join Qgeolistest developper for CEA!

**Comment by delhomer** [comment]
Hello @Bernard13090,

Thank you for your interest for QGeoloGIS!

If you need some assistance with this tool or if you want to report a bug, please consider the following repo: https://gitlab.com/Oslandia/qgis/QGeoloGIS/.

Actually the problem you mention has already been addressed through other issues. You should have a look at https://gitlab.com/Oslandia/qgis/QGeoloGIS/-/issues/82 or https://gitlab.com/Oslandia/qgis/QGeoloGIS/-/issues/87, for instance!

Be careful then, we are progressively dropping the support on QGeoloGIS, and focusing on the development of a brand new tool for visualizing geological survey, [Openlog](https://gitlab.com/geolandia/openlog/).

**Comment by Bernard13090** [comment]
Raphael,
J'ai suivi le tuto à la lettre.

je suis sur WIN10 et j'ai bien crée mon fichier de **pg_service.conf**
**_`#
#	Connection configuration file

#

[qgeologistest]
host=127.0.0.1
user=Bernard
password=Gxxx
dbname=qgeologistest
port=5432`_**

Par ailleurs en ligne de commande, j'arrive à me connecter avec PostgreSQL sous python en utilisant.
`
**_C:\Users\Bernard\Cmder
λ psql service=qgeologistest
psql (15.2)
Attention : l'encodage console (850) diffère de l'encodage Windows (1252).
            Les caractères 8 bits peuvent ne pas fonctionner correctement.
            Voir la section « Notes aux utilisateurs de Windows » de la page
            référence de psql pour les détails.
Saisissez « help » pour l'aide.

qgeologistest=#`_**

donc le service fonctionne.

Parc contre avec : generate_config_test.py
**conn = psycopg2.connect("service=qgeologistest")
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: definition of service "qgeologistest" not found**


J'ai l'impression que dans: "**generate_config_test.py**" le service n'est pas pris en charge n'admet pas la connexion au service.
